# SPDX-License-Identifier: LGPL-2.1-or-later
"""The console's stylesheet: the design, as CSS.

Extracted verbatim from `design/kernelci-design.html` (md5 `f9cb7459b2f7a92c0abe3d5afb541532`, 197552 bytes) by
`tools/design_extract.py` - do not edit this file, edit the board and re-extract,
because the two are compared by `python3 tools/design_extract.py --check`.

The only rules left out are the nine that draw the *board* rather than a screen:
`.sheet*` (the numbered captions) and `.frame*` (the mock browser window each
screen is drawn inside).  A console that renders itself inside a picture of a
browser is a joke at the reader's expense.

What is here is the designer's own text: the four token blocks (`:root`, the
`prefers-color-scheme` block, `[data-theme=dark]`, `[data-theme=light]`) and the
component layer below them.  Tokens are not re-declared in Python - a colour that
exists twice is a colour that will disagree with itself.
"""

CSS = r""":root {
  --ground: #eceef1;
  --surface: #ffffff;
  --raised: #f7f8fa;
  --sunken: #e3e6ea;
  --line: #c9ced6;
  --line-soft: #dde1e7;
  --ink: #14171c;
  --ink-mid: #48505c;
  --ink-soft: #6b7482;
  --ink-inv: #ffffff;
  --accent: #2f5bd0;
  --accent-soft: #e6ecfb;
  --accent-line: #b9c8f0;
  --ok: #146c43;
  --ok-soft: #e2f2e9;
  --warn: #8a5400;
  --warn-soft: #faefdc;
  --bad: #a5241c;
  --bad-soft: #fbe6e4;
  --info: #1f5f8b;
  --info-soft: #e2eff7;
  --idle: #5c6572;
  --idle-soft: #e9ebef;
  --s1: #2f5bd0;
  --s2: #7a4bc4;
  --s3: #0f7b8a;
  --s4: #b06000;
  --s5: #8a3a6b;
  --code: #3f4a5a;
  --code-soft: #eef0f3;
    --r: 6px;
    --r-sm: 4px;
    --r-pill: 999px;
    --sans: "IBM Plex Sans",system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
    --mono: "IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
    --shadow: 0 1px 2px rgba(15,18,23,.05),0 6px 16px -10px rgba(15,18,23,.25);
    --shadow-pop: 0 4px 10px rgba(15,18,23,.10),0 16px 32px -12px rgba(15,18,23,.30);
    --topbar-h: 46px;
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --ground: #101318;
    --surface: #191d24;
    --raised: #1f242c;
    --sunken: #141820;
    --line: #333a45;
    --line-soft: #282e38;
    --ink: #e7ebf1;
    --ink-mid: #a9b2bf;
    --ink-soft: #79828f;
    --ink-inv: #0d1015;
    --accent: #7ea2ff;
    --accent-soft: #1d2942;
    --accent-line: #33446b;
    --ok: #5cc08a;
    --ok-soft: #142c20;
    --warn: #d7a153;
    --warn-soft: #2e2416;
    --bad: #e88078;
    --bad-soft: #331917;
    --info: #6fb6e8;
    --info-soft: #152734;
    --idle: #8b94a2;
    --idle-soft: #232830;
    --s1: #8fb0ff;
    --s2: #b79bf0;
    --s3: #4fc3d4;
    --s4: #e0a15c;
    --s5: #e08cbb;
    --code: #c2cad6;
    --code-soft: #1b2028;
    --r: 6px;
    --r-sm: 4px;
    --r-pill: 999px;
    --sans: "IBM Plex Sans",system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
    --mono: "IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
    --shadow: 0 1px 2px rgba(15,18,23,.05),0 6px 16px -10px rgba(15,18,23,.25);
    --shadow-pop: 0 4px 10px rgba(15,18,23,.10),0 16px 32px -12px rgba(15,18,23,.30);
    --topbar-h: 46px;
    color-scheme: dark;
  }
}
:root[data-theme="dark"] {
    --ground: #101318;
    --surface: #191d24;
    --raised: #1f242c;
    --sunken: #141820;
    --line: #333a45;
    --line-soft: #282e38;
    --ink: #e7ebf1;
    --ink-mid: #a9b2bf;
    --ink-soft: #79828f;
    --ink-inv: #0d1015;
    --accent: #7ea2ff;
    --accent-soft: #1d2942;
    --accent-line: #33446b;
    --ok: #5cc08a;
    --ok-soft: #142c20;
    --warn: #d7a153;
    --warn-soft: #2e2416;
    --bad: #e88078;
    --bad-soft: #331917;
    --info: #6fb6e8;
    --info-soft: #152734;
    --idle: #8b94a2;
    --idle-soft: #232830;
    --s1: #8fb0ff;
    --s2: #b79bf0;
    --s3: #4fc3d4;
    --s4: #e0a15c;
    --s5: #e08cbb;
    --code: #c2cad6;
    --code-soft: #1b2028;
    --r: 6px;
    --r-sm: 4px;
    --r-pill: 999px;
    --sans: "IBM Plex Sans",system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
    --mono: "IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
    --shadow: 0 1px 2px rgba(15,18,23,.05),0 6px 16px -10px rgba(15,18,23,.25);
    --shadow-pop: 0 4px 10px rgba(15,18,23,.10),0 16px 32px -12px rgba(15,18,23,.30);
    --topbar-h: 46px;
  color-scheme: dark;
}
:root[data-theme="light"] {
  color-scheme: light;
}

*, *::before, *::after { box-sizing: border-box; }

html { -webkit-text-size-adjust: 100%; }

body {
  margin: 0;
  background: var(--ground);
  color: var(--ink);
  font-family: var(--sans);
  font-size: 13px;
  line-height: 1.5;
  font-variant-numeric: tabular-nums;
  -webkit-font-smoothing: antialiased;
}

h1, h2, h3, p, ul, ol, figure { margin: 0; }
ul, ol { padding: 0; list-style: none; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
b, strong { font-weight: 600; }
code, kbd, samp, pre, .mono { font-family: var(--mono); }
code { font-size: .94em; color: var(--code); }
hr { border: 0; border-top: 1px solid var(--line-soft); margin: 12px 0; }
:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }

.sr { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); }
.num { font-variant-numeric: tabular-nums; }
.nowrap { white-space: nowrap; }
.muted { color: var(--ink-soft); }
.mid { color: var(--ink-mid); }
.right { text-align: right; }
.grow { flex: 1 1 auto; min-width: 0; }
.row { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.row.tight { gap: 6px; }
.stack { display: flex; flex-direction: column; gap: 12px; }

.topbar {
  position: sticky; top: 0; z-index: 40;
  display: flex; align-items: center; gap: 14px;
  height: var(--topbar-h); padding: 0 16px;
  background: var(--surface);
  border-bottom: 1px solid var(--line);
}
.brand { display: flex; align-items: baseline; gap: 8px; min-width: 0; }
.brand .mark {
  font-family: var(--mono); font-size: 11px; font-weight: 500;
  letter-spacing: .04em; text-transform: uppercase;
  color: var(--ink-inv); background: var(--accent);
  border-radius: var(--r-sm); padding: 2px 6px;
}
.brand .name { font-size: 13.5px; font-weight: 600; letter-spacing: -.01em; }

.nav { display: flex; align-items: center; gap: 2px; }
.nav a {
  padding: 5px 10px; border-radius: var(--r-sm);
  font-size: 12.5px; color: var(--ink-mid); white-space: nowrap;
}
.nav a:hover { background: var(--raised); color: var(--ink); text-decoration: none; }
.nav a[aria-current="page"] {
  background: var(--accent-soft); color: var(--accent); font-weight: 600;
}

.topbar .tools { display: flex; align-items: center; gap: 8px; margin-left: auto; }

.pulse {
  width: 6px; height: 6px; border-radius: 50%; background: var(--info);
  flex: 0 0 auto; animation: pulse 1.6s ease-in-out infinite;
}
@keyframes pulse { 0%,100% { opacity: 1 } 50% { opacity: .25 } }
@media (prefers-reduced-motion: reduce) { .pulse { animation: none } }

.live-chip {
  display: inline-flex; align-items: center; gap: 6px;
  padding: 3px 9px 3px 8px; border-radius: var(--r-pill);
  border: 1px solid var(--info); background: var(--info-soft);
  color: var(--info); font-size: 11.5px; font-weight: 500;
}
.live-chip:hover { text-decoration: none; filter: brightness(1.03); }

.wrap { max-width: 1680px; margin: 0 auto; padding: 14px 16px 48px; }

.live {
  border: 1px solid var(--line); border-radius: var(--r);
  background: var(--surface); margin-bottom: 12px;
}
.live > summary {
  display: flex; align-items: center; gap: 9px;
  padding: 8px 12px; cursor: pointer; list-style: none; font-size: 12.5px;
}
.live > summary::-webkit-details-marker { display: none; }
.live > summary::after {
  content: ""; margin-left: auto; width: 6px; height: 6px;
  border-right: 1.5px solid var(--ink-soft); border-bottom: 1.5px solid var(--ink-soft);
  transform: rotate(45deg) translate(-2px, -2px);
}
.live[open] > summary { border-bottom: 1px solid var(--line-soft); }
.live[open] > summary::after { transform: rotate(-135deg) translate(-2px, -2px); }

.acts { display: flex; flex-direction: column; }
.act {
  display: grid; grid-template-columns: 16px 84px minmax(0,1fr) 78px auto;
  align-items: center; gap: 10px; padding: 7px 12px;
  border-top: 1px solid var(--line-soft);
}
.acts .act:first-child { border-top: 0; }
.act .who { font-family: var(--mono); font-size: 11.5px; color: var(--ink-mid); }
.act .what { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  font-size: 12.5px; color: var(--ink); }
.act .what a { color: inherit; }
.act .argv { font-family: var(--mono); font-size: 11px; color: var(--ink-soft);
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.act .age { font-family: var(--mono); font-size: 11.5px; color: var(--ink-soft); text-align: right; }
.act .do { display: flex; gap: 6px; justify-self: end; }
@media (max-width: 940px) { .act { grid-template-columns: 16px 1fr auto; } .act .argv { display: none } }

.panel {
  background: var(--surface); border: 1px solid var(--line);
  border-radius: var(--r); box-shadow: var(--shadow); overflow: hidden;
}
.panel + .panel { margin-top: 12px; }
.panel > .head {
  display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
  padding: 9px 12px; border-bottom: 1px solid var(--line-soft); background: var(--surface);
}
.panel > .head h2 { font-size: 12.5px; font-weight: 600; letter-spacing: -.005em; }
.panel > .head .sub { font-size: 11.5px; color: var(--ink-soft); }
.panel > .head .tools { margin-left: auto; display: flex; align-items: center; gap: 8px; }
.panel > .body { padding: 12px; }
.panel > .body.flush { padding: 0; }

details.panel > summary.head { cursor: pointer; list-style: none; }
details.panel > summary.head::-webkit-details-marker { display: none; }
details.panel > summary.head::before {
  content: ""; width: 6px; height: 6px; flex: 0 0 auto;
  border-right: 1.5px solid var(--ink-soft); border-bottom: 1.5px solid var(--ink-soft);
  transform: rotate(-45deg);
}
details.panel[open] > summary.head::before { transform: rotate(45deg) translate(-1px,-1px); }
details.panel > summary.head:hover { background: var(--raised); }

button, input, select, textarea { font: inherit; color: inherit; }

.btn {
  display: inline-flex; align-items: center; gap: 6px;
  background: var(--surface); border: 1px solid var(--line); border-radius: var(--r-sm);
  padding: 4px 10px; font-size: 12px; color: var(--ink-mid); cursor: pointer;
  white-space: nowrap;
}
.btn:hover { border-color: var(--accent); color: var(--accent); }
.btn.primary { background: var(--accent); border-color: var(--accent); color: var(--ink-inv); font-weight: 500; }
.btn.primary:hover { filter: brightness(1.08); color: var(--ink-inv); }
.btn.ghost { background: transparent; border-color: transparent; color: var(--ink-soft); }
.btn.ghost:hover { background: var(--raised); color: var(--ink); border-color: transparent; }
.btn.danger:hover { border-color: var(--bad); color: var(--bad); }
.btn.sm { padding: 2px 7px; font-size: 11.5px; }
.btn[disabled] { opacity: .5; cursor: not-allowed; }

input[type="text"], input[type="number"], input[type="search"], select, textarea {
  background: var(--sunken); border: 1px solid var(--line); border-radius: var(--r-sm);
  padding: 4px 7px; font-size: 12px; min-width: 0; width: 100%;
}
input::placeholder { color: var(--ink-soft); }
input:focus, select:focus, textarea:focus {
  outline: 2px solid var(--accent); outline-offset: -1px; border-color: var(--accent);
}
select {
  appearance: none; padding-right: 22px; cursor: pointer;
  background-image: linear-gradient(45deg, transparent 50%, var(--ink-soft) 50%),
                    linear-gradient(135deg, var(--ink-soft) 50%, transparent 50%);
  background-position: calc(100% - 13px) 52%, calc(100% - 8px) 52%;
  background-size: 5px 5px, 5px 5px; background-repeat: no-repeat;
}
input[type="number"] { font-family: var(--mono); }
textarea { font-family: var(--mono); font-size: 11.5px; line-height: 1.5; resize: vertical; }

.filters {
  display: flex; flex-wrap: wrap; gap: 8px; align-items: flex-end;
  padding: 10px 12px; border-bottom: 1px solid var(--line-soft);
}
.f { display: flex; flex-direction: column; gap: 3px; min-width: 0; }
.f > .lbl {
  font-size: 10px; font-weight: 600; letter-spacing: .06em; text-transform: uppercase;
  color: var(--ink-soft);
}
.f.w-sm { flex: 0 0 84px; }
.f.w-md { flex: 0 0 122px; }
.f.w-lg { flex: 0 1 190px; }
.f.w-xl { flex: 1 1 240px; }
.f.cb { flex-direction: row; align-items: center; gap: 6px; padding-bottom: 5px; }

.multi { position: relative; }
.multi > .box {
  display: flex; align-items: center; gap: 5px; flex-wrap: wrap;
  min-height: 27px; padding: 2px 5px;
  background: var(--sunken); border: 1px solid var(--line); border-radius: var(--r-sm);
}
.multi > .box:focus-within { outline: 2px solid var(--accent); outline-offset: -1px; }
.multi input { border: 0; background: transparent; padding: 2px 2px; flex: 1 1 54px; width: auto; }
.multi input:focus { outline: none; }
.tag {
  display: inline-flex; align-items: center; gap: 4px;
  background: var(--accent-soft); color: var(--accent); border: 1px solid var(--accent-line);
  border-radius: var(--r-sm); padding: 1px 4px 1px 6px; font-size: 11.5px;
}
.tag button {
  border: 0; background: none; cursor: pointer; color: inherit;
  font-size: 13px; line-height: 1; padding: 0 2px; opacity: .6;
}
.tag button:hover { opacity: 1; }
.multi .menu {
  position: absolute; z-index: 30; top: calc(100% + 4px); left: 0; min-width: 180px;
  max-height: 260px; overflow: auto; padding: 4px;
  background: var(--surface); border: 1px solid var(--line);
  border-radius: var(--r); box-shadow: var(--shadow-pop);
}
.multi .menu:empty, .multi .menu[hidden] { display: none; }
.multi .menu button {
  display: block; width: 100%; text-align: left; border: 0; background: none;
  padding: 5px 8px; border-radius: var(--r-sm); font-size: 12px; color: var(--ink-mid); cursor: pointer;
}
.multi .menu button:hover, .multi .menu button[aria-selected="true"] {
  background: var(--accent-soft); color: var(--accent);
}

.f > .seg { align-self: flex-start; }
.seg { display: inline-flex; border: 1px solid var(--line); border-radius: var(--r-sm); overflow: hidden; }
.seg label { display: flex; }
.seg input { position: absolute; opacity: 0; pointer-events: none; }
.seg span {
  padding: 4px 9px; font-size: 11.5px; color: var(--ink-mid); cursor: pointer;
  border-left: 1px solid var(--line); background: var(--surface);
}
.seg label:first-child span { border-left: 0; }
.seg input:checked + span { background: var(--accent-soft); color: var(--accent); font-weight: 500; }
.seg input:focus-visible + span { outline: 2px solid var(--accent); outline-offset: -2px; }

.chips { display: flex; flex-wrap: wrap; gap: 8px; }
.chip {
  display: flex; align-items: baseline; gap: 7px;
  padding: 7px 11px; border: 1px solid var(--line); border-radius: var(--r);
  background: var(--surface); box-shadow: var(--shadow); color: inherit;
}
.chip:hover { border-color: var(--accent-line); text-decoration: none; }
.chip .k { font-size: 11px; color: var(--ink-soft); }
.chip .v { font-size: 16px; font-weight: 600; font-variant-numeric: tabular-nums; letter-spacing: -.02em; }
.chip.set { background: var(--accent-soft); border-color: var(--accent-line); }
.chip.set .v, .chip.set .k { color: var(--accent); }

.pill {
  display: inline-flex; align-items: center; gap: 4px;
  padding: 1px 7px; border-radius: var(--r-pill);
  font-size: 11px; font-weight: 500; white-space: nowrap;
  border: 1px solid transparent;
}
.pill::before { content: ""; width: 5px; height: 5px; border-radius: 50%; background: currentColor; flex: 0 0 auto; }
.pill.bare::before { display: none; }
.pill.ok   { color: var(--ok);   background: var(--ok-soft);   border-color: var(--ok); }
.pill.warn { color: var(--warn); background: var(--warn-soft); border-color: var(--warn); }
.pill.bad  { color: var(--bad);  background: var(--bad-soft);  border-color: var(--bad); }
.pill.info { color: var(--info); background: var(--info-soft); border-color: var(--info); }
.pill.idle { color: var(--idle); background: var(--idle-soft); border-color: var(--idle); }
.pill.plain { color: var(--ink-mid); background: var(--sunken); border-color: var(--line); }
.pill .n { font-variant-numeric: tabular-nums; opacity: .85; }

.tick { color: var(--ok); font-weight: 600; }
.cross { color: var(--bad); font-weight: 600; }
.dash { color: var(--ink-soft); }

.tscroll { overflow-x: auto; }
.pager {
  display: flex; align-items: center; gap: 6px;
  padding: 7px 14px; border-top: 1px solid var(--line-soft); background: var(--raised);
}
.pager .pages { display: flex; gap: 4px; }
.pager .btn { min-width: 24px; justify-content: center; font-variant-numeric: tabular-nums; }
.pager .btn.on { background: var(--accent); border-color: var(--accent); color: var(--ink-inv); }
.pager .btn.on:hover { color: var(--ink-inv); }
.pager .pjumpwrap { display: flex; align-items: center; gap: 5px; margin-left: 4px; }
.pager .pjump {
  width: 44px; padding: 2px 5px; text-align: center;
  font-size: 11.5px; font-variant-numeric: tabular-nums;
  background: var(--surface); border: 1px solid var(--line);
  border-radius: var(--r-sm); color: var(--ink-mid);
}
.pager .pjump:focus { outline: none; border-color: var(--accent); color: var(--accent); }
.pager .ptotal { font-size: 11.5px; color: var(--ink-soft); font-variant-numeric: tabular-nums; }
table.grid { width: 100%; border-collapse: separate; border-spacing: 0; font-size: 12.5px; }
table.grid th, table.grid td {
  padding: 7px 10px; text-align: left; vertical-align: top;
  border-bottom: 1px solid var(--line-soft);
}
table.grid thead th {
  position: sticky; top: var(--topbar-h); z-index: 10;
  background: var(--raised); color: var(--ink-soft);
  font-size: 10px; font-weight: 600; letter-spacing: .06em; text-transform: uppercase;
  white-space: nowrap; border-bottom: 1px solid var(--line);
}
table.grid tbody tr:hover { background: var(--raised); }
table.grid tbody tr:last-child td { border-bottom: 0; }
table.grid td.n, table.grid th.n { text-align: right; font-variant-numeric: tabular-nums; font-family: var(--mono); font-size: 11.5px; }
table.grid td.c, table.grid th.c { text-align: center; }
table.grid th.sortable { cursor: pointer; user-select: none; }
table.grid th.sortable:hover { color: var(--accent); }
table.grid th .arw { color: var(--accent); margin-left: 3px; }
table.grid .id { font-family: var(--mono); font-size: 11.5px; color: var(--code); }
table.grid .id a { color: inherit; }
table.grid .id a:hover { color: var(--accent); }
table.grid .tree { font-weight: 500; }
table.grid .br { color: var(--ink-soft); font-family: var(--mono); font-size: 11px; }
table.grid td.wrapc { white-space: normal; min-width: 160px; max-width: 340px; }
table.grid td.trunc { max-width: 260px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
table.grid .acts-cell { white-space: nowrap; }
table.grid .acts-cell a, table.grid .acts-cell button { margin-right: 6px; }
table.grid .flag {
  display: inline-grid; place-items: center; width: 16px; height: 16px;
  border-radius: var(--r-sm); font-size: 10.5px; line-height: 1;
  background: var(--sunken); color: var(--ink-soft); border: 1px solid var(--line);
}
table.grid .flag.on { background: var(--ok-soft); color: var(--ok); border-color: var(--ok); }
table.grid .flag.no { background: var(--bad-soft); color: var(--bad); border-color: var(--bad); }

table.grid tr.group td {
  background: var(--raised); font-size: 11px; font-weight: 600;
  letter-spacing: .05em; text-transform: uppercase; color: var(--ink-soft);
}

.delta { display: inline-flex; gap: 6px; font-family: var(--mono); font-size: 11.5px; }
.delta .plus { color: var(--ok); }
.delta .minus { color: var(--bad); }
.delta .same { color: var(--ink-soft); }

.spark { display: inline-flex; gap: 2px; align-items: center; }
.spark i {
  width: 9px; height: 14px; border-radius: 2px; background: var(--idle-soft);
  border: 1px solid var(--line);
}
.spark i.ok { background: var(--ok); border-color: var(--ok); }
.spark i.bad { background: var(--bad); border-color: var(--bad); }
.spark i.warn { background: var(--warn); border-color: var(--warn); }

details.more { border-bottom: 1px solid var(--line-soft); }
details.more > summary {
  display: flex; align-items: center; gap: 6px; cursor: pointer; list-style: none;
  padding: 6px 12px; font-size: 11px; font-weight: 600; letter-spacing: .06em;
  text-transform: uppercase; color: var(--ink-soft);
}
details.more > summary::-webkit-details-marker { display: none; }
details.more > summary::before {
  content: ""; width: 5px; height: 5px;
  border-right: 1.5px solid var(--ink-soft); border-bottom: 1.5px solid var(--ink-soft);
  transform: rotate(-45deg);
}
details.more[open] > summary::before { transform: rotate(45deg) translate(-1px,-1px); }
details.more > summary:hover { color: var(--accent); }
details.more > summary:hover::before { border-color: var(--accent); }
details.more .filters { border-bottom: 0; background: var(--raised); padding-top: 9px; }

.panel > .body.flush > .note { margin: 10px 12px 0; }

.bars { display: flex; flex-direction: column; gap: 7px; }
.bar { display: grid; grid-template-columns: minmax(90px, 200px) 1fr 54px; align-items: center; gap: 10px; }
.bar .bt { font-family: var(--mono); font-size: 11.5px; color: var(--code);
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.bar .track { height: 9px; background: var(--sunken); border-radius: var(--r-pill); overflow: hidden; display: flex; }
.bar .track i { display: block; height: 100%; }
.bar .track i.ok { background: var(--ok); }
.bar .track i.bad { background: var(--bad); }
.bar .track i.warn { background: var(--warn); }
.bar .track i.idle { background: var(--idle); }
.bar .bn { text-align: right; font-family: var(--mono); font-size: 11.5px; color: var(--ink-mid); }

.kv { display: flex; flex-direction: column; }
.kv > div {
  display: grid; grid-template-columns: minmax(120px, 210px) minmax(0,1fr);
  gap: 12px; padding: 6px 0; border-top: 1px solid var(--line-soft);
}
.kv > div:first-child { border-top: 0; }
.kv dt { font-size: 11.5px; color: var(--ink-soft); }
.kv dd { margin: 0; font-family: var(--mono); font-size: 11.5px; color: var(--ink); word-break: break-all; }
.note {
  display: flex; gap: 8px; align-items: flex-start;
  padding: 8px 11px; border-radius: var(--r-sm);
  background: var(--accent-soft); border: 1px solid var(--accent-line);
  color: var(--ink-mid); font-size: 11.5px; line-height: 1.55;
}
.note b { color: var(--accent); }
.note.warn { background: var(--warn-soft); border-color: var(--warn); }
.note.warn b { color: var(--warn); }
.empty { padding: 18px 12px; text-align: center; color: var(--ink-soft); font-size: 12.5px; }
kbd {
  font-family: var(--mono); font-size: 10.5px; background: var(--sunken);
  border: 1px solid var(--line); border-radius: 3px; padding: 1px 4px; color: var(--ink-mid);
}
.q { font-family: var(--mono); font-size: 11.5px; color: var(--ink-soft); }

.split { display: grid; grid-template-columns: minmax(0,1fr) 320px; gap: 12px; align-items: start; }
@media (max-width: 1180px) { .split { grid-template-columns: minmax(0,1fr); } }

.foot {
  display: flex; gap: 12px; flex-wrap: wrap; align-items: baseline;
  margin-top: 14px; padding-top: 10px; border-top: 1px solid var(--line-soft);
  font-size: 11px; color: var(--ink-soft);
}

body { background: var(--ground); }
@media print { }

li.logrow { background: var(--sunken); border-top: 1px solid var(--line-soft); }
table.grid tbody tr.logrow > td { padding: 0; background: var(--sunken); border-top: 1px solid var(--line-soft); }
table.grid tbody tr.logrow:hover { background: var(--sunken); }
.logbox { display: flex; flex-direction: column; gap: 7px; padding: 10px 14px 11px; }
.logbox pre { margin: 0; max-height: 168px; overflow: auto; font-family: var(--mono); font-size: 11.5px; line-height: 1.6; color: var(--ink-mid); white-space: pre; }
.logbox .logfoot { display: flex; align-items: center; gap: 7px; font-size: 11.5px; color: var(--ink-soft); }
.logbox .logfoot code { color: var(--code); }
.chart { display: block; width: 100%; height: auto; }
.chart text { font-family: var(--mono); font-size: 10px; fill: var(--ink-soft); }
.chart .yline { stroke: var(--line-soft); stroke-width: 1; stroke-dasharray: 3 4; }
.chart .axis { stroke: var(--line); stroke-width: 1; }
.chart .endlbl { fill: var(--ink-mid); }
.legend { display: flex; flex-wrap: wrap; gap: 6px 16px; padding-bottom: 10px; }
.legend .lg { display: inline-flex; align-items: center; gap: 6px; font-size: 11.5px; color: var(--ink-mid); }
.legend .lg i { width: 15px; height: 2px; border-radius: 2px; flex: 0 0 auto; }
.legend .lg code { color: var(--ink); }
.chartcap { text-align: center; font-size: 11px; color: var(--ink-soft); padding-top: 7px; }
"""
