#!/usr/bin/env python3
"""Render a tracked config template into the runtime file a deployment uses.

kernelci's plain ``toml.load()`` expands no environment variables, so the
settings file has to carry absolute values.  Placeholders are ``@NAME@``,
filled from ``--var NAME=VALUE`` plus ``KCI_ROOT`` - never from the ambient
environment, and a name with no value is an error, not something left in place.

Rationale: docs/code-notes/W2d-tools.md.

    python3 scripts/tools/render-local-config.py --template config/local-callback.toml \\
        --output work/local-callback.toml --var KCI_ROOT=/srv/kernelci-riscv
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))  # scripts/ holds kcilib

from kcilib import repo_root

# Walked up to run.sh, never counted: this file lives in scripts/tools/, and a
# counted root rendered every @KCI_ROOT@ as .../scripts, so the stack's settings
# pointed at scripts/kernelci-pipeline/data/ssh/... and every job node came back
# submit_error.  See kcilib.repo_root().
ROOT = repo_root()
TOKEN_RE = re.compile(r"@([A-Z][A-Z0-9_]*)@")


def strip_template_banner(text, template):
    """Replace the template's own banner with a generated-file header.

    The templates open with a comment block that says they are NOT the file used
    at runtime.  That sentence is true of the template and a lie inside
    work/local-callback.toml, which IS what the callback and the scheduler read -
    anyone debugging there reads it first.
    """
    lines = text.splitlines(keepends=True)
    end = 0
    while end < len(lines) and lines[end].lstrip().startswith("#"):
        end += 1
    banner = "".join(lines[:end])
    if "TEMPLATE" not in banner.upper():
        return text
    header = (
        "# GENERATED by scripts/tools/render-local-config.py - do not edit.\n"
        f"# Source: {os.path.relpath(template, ROOT)}\n"
        "#\n"
        "# Edit the template instead; this file is rewritten every ./run.sh stack.\n\n"
    )
    return header + "".join(lines[end:])


def render(text, values):
    """Substitute every @NAME@ in *text*; None when the template has none."""
    names = {match.group(1) for match in TOKEN_RE.finditer(text)}
    if not names:
        return None
    missing = sorted(name for name in names if not values.get(name))
    if missing:
        sys.exit(
            "no value for "
            + ", ".join(f"@{name}@" for name in missing)
            + " (pass --var NAME=VALUE or set it in the environment)"
        )
    return TOKEN_RE.sub(lambda match: values[match.group(1)], text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--template",
        default=os.path.join(ROOT, "config", "local-callback.toml"),
        help="template to render (default: config/local-callback.toml)",
    )
    parser.add_argument(
        "--output",
        default=os.path.join(ROOT, "work", "local-callback.toml"),
        help="rendered file (default: work/local-callback.toml)",
    )
    parser.add_argument(
        "--var",
        action="append",
        default=[],
        metavar="NAME=VALUE",
        help="value for a placeholder; may be repeated",
    )
    args = parser.parse_args()

    values = {"KCI_ROOT": ROOT}
    for item in args.var:
        if "=" not in item:
            sys.exit(f"--var expects NAME=VALUE, got {item!r}")
        name, value = item.split("=", 1)
        values[name] = value

    if not os.path.exists(args.template):
        sys.exit(f"template not found: {args.template}")
    with open(args.template, encoding="utf-8") as handle:
        template_text = handle.read()
    rendered = render(template_text, values)
    if rendered is None:
        sys.exit(
            f"{args.template} contains no @NAME@ placeholder; refusing to "
            "render (it would keep whatever absolute values it carries)"
        )
    rendered = strip_template_banner(rendered, args.template)
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"OK  rendered {args.output} from {args.template}")


if __name__ == "__main__":
    main()
