#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""The design's stylesheet, read out of the board instead of retyped.

    python3 tools/design_extract.py                  # write lib/gui/design/style.py
    python3 tools/design_extract.py --check          # fail if what ships is not the design
    python3 tools/design_extract.py --pages DIR      # the board's five screens, indented

`design/kernelci-design.html` is the design of record: one self-contained page
that draws every screen of this console, with its stylesheet inlined.  The
console needs that stylesheet, and 24 KB of CSS retyped by hand is 24 KB of CSS
that starts disagreeing with the board the first time either side is edited - so
this reads the board and writes `lib/gui/design/style.py`.

Nine rules are dropped on the way, and only nine: the ones that draw the *board*
rather than a screen - `.sheet*` (the numbered captions over each screen) and
`.frame*` (the mock browser window each screen sits inside).  Everything else,
the token blocks included, is copied byte for byte: the design's light/dark/auto
handling is already correct where it is, and a colour declared a second time in
Python is a colour that will disagree with itself.

`--check` is the gate.  It rebuilds the module in memory and compares it with the
file on disk, so a board that has moved on since the last extraction fails here
instead of quietly shipping a console that no longer looks like its own design.

`--pages DIR` writes the board's five screens out again as indented files.  The
board is one self-contained page whose markup lives on a handful of very long
lines - fine for a browser, unreadable for the person porting a screen into
`lib/gui/design/pages/` - so the same text is written one screen per file, one
element per line.  It is a working copy and not a source: nothing reads it back.

Exit status is 0 when the file is what the board says, 1 when it is not (with the
first differing line printed, because "out of date" is not an instruction), and 2
when the board itself cannot be read.
"""

import argparse
import difflib
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOARD = os.path.join(ROOT, "design", "kernelci-design.html")
OUT = os.path.join(ROOT, "lib", "gui", "design", "style.py")

# A board device, not a screen: the caption block and the fake browser window.
DROPPED = re.compile(r"\.(sheet|frame|board|jump|cover)\b")

HEADER = '''# SPDX-License-Identifier: LGPL-2.1-or-later
"""The console's stylesheet: the design, as CSS.

Extracted verbatim from `{board}` (md5 `{digest}`, {size} bytes) by
`tools/design_extract.py` - do not edit this file, edit the board and re-extract,
because the two are compared by `python3 tools/design_extract.py --check`.

The only rules left out are the nine that draw the *board* rather than a screen:
`.sheet*` (the numbered captions) and `.frame*` (the mock browser window each
screen is drawn inside).  A console that renders itself inside a picture of a
browser is a joke at the reader's expense.

What is here is the designer's own text: the four token blocks (`:root`, the
`prefers-color-scheme` block, `[data-theme=dark]`, `[data-theme=light]`) and the
component layer below them.  Tokens are not re-declared in Python - a colour that
exists twice is a colour that will disagree with itself.
"""

'''


def stylesheet(board_text: str) -> str:
    """The board's `<style>` with the nine board-only rules removed, everything else kept.

    Blocks are walked with a brace counter rather than matched with a regex,
    because an at-rule (`@media (prefers-color-scheme: dark)`) contains braces of
    its own and a regex that deletes "the rule with this selector" happily deletes
    the dark theme with it.  An at-rule is recursed into instead, so a board rule
    nested in a media query is dropped and the media query survives.
    """
    found = re.search(r"<style>(.*?)</style>", board_text, re.DOTALL)
    if not found:
        raise ValueError("the board has no <style> block")
    return _strip(found.group(1)).strip() + "\n"


def _strip(text: str) -> str:
    out, i, n = [], 0, len(text)
    while i < n:
        brace = text.find("{", i)
        if brace < 0:
            out.append(text[i:])
            break
        selector = text[i:brace]
        depth, j = 1, brace + 1
        while j < n and depth:
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
            j += 1
        body = text[brace + 1:j - 1]
        if selector.lstrip().startswith("@"):
            out.append(selector + "{" + _strip(body) + "}")
        elif not DROPPED.search(selector):
            out.append(selector + "{" + body + "}")
        i = j
    return "".join(out)


def render(board_text: str) -> str:
    """The whole module: the header recording the source, then the CSS as a raw string."""
    digest = hashlib.md5(board_text.encode("utf-8")).hexdigest()
    header = HEADER.format(board=os.path.relpath(BOARD, ROOT).replace(os.sep, "/"),
                           digest=digest, size=len(board_text.encode("utf-8")))
    css = stylesheet(board_text)
    if '"""' in css:
        raise ValueError("the board's CSS contains a triple quote; the module needs another quoting")
    return f'{header}CSS = r"""{css}"""\n'


SHEET = re.compile(r'<div class="sheet" id="(\w+)">')
VOID = frozenset(["area", "base", "br", "col", "embed", "hr", "img", "input",
                  "link", "meta", "source", "track", "wbr"])


def screens(board_text: str) -> dict:
    """The board's screens as `{slug: markup}`: one sheet div up to the next.

    A slice of the original text rather than a re-render, so what the reader of an
    extract sees is what the board says, byte for byte.
    """
    marks = [(m.group(1), m.start()) for m in SHEET.finditer(board_text)]
    if not marks:
        raise ValueError("the board has no sheets")
    return {slug: board_text[start:(marks[i + 1][1] if i + 1 < len(marks) else len(board_text))]
            for i, (slug, start) in enumerate(marks)}


def indented(markup: str) -> str:
    """One element per line, nested by depth - written for a reader, not a parser.

    Text stays on its own line under the element that carries it, so a screen whose
    real markup is four very long lines becomes something a person can skim while
    porting it into a page module.
    """
    lines, depth = [], 0
    for token in re.findall(r"<[^>]+>|[^<]+", markup):
        if token.startswith("</"):
            depth = max(0, depth - 1)
            lines.append("  " * depth + token)
        elif token.startswith("<"):
            lines.append("  " * depth + token)
            name = re.match(r"<\s*([a-zA-Z0-9-]+)", token)
            if name and name.group(1).lower() not in VOID and not token.rstrip().endswith("/>"):
                depth += 1
        elif token.strip():
            lines.append("  " * depth + token.strip())
    return "\n".join(lines) + "\n"


def write_pages(board_text: str, out_dir: str) -> int:
    """One file per screen under `out_dir`; the count, names and sizes are printed."""
    os.makedirs(out_dir, exist_ok=True)
    found = screens(board_text)
    for slug, markup in sorted(found.items()):
        path = os.path.join(out_dir, f"{slug}.html")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(indented(markup))
        print(f"  {slug:10s} {os.path.getsize(path):>7,} bytes  {path}")
    print(f"wrote {len(found)} screen(s) under {out_dir}")
    return 0


def check(written: str, wanted: str) -> int:
    """0 when the shipped file is what the board says, 1 when it is not.

    The first differing line is printed with both sides: a gate that only says
    "out of date" leaves the reader to diff 570 lines by eye.
    """
    if written == wanted:
        print(f"design: lib/gui/design/style.py matches {os.path.relpath(BOARD, ROOT)}")
        return 0
    print("X lib/gui/design/style.py is not what the board says", file=sys.stderr)
    diff = difflib.unified_diff(written.splitlines(), wanted.splitlines(),
                                "style.py (on disk)", "style.py (from the board)", lineterm="", n=1)
    for line in list(diff)[:24]:
        print("  " + line, file=sys.stderr)
    print(f"  run: python3 {os.path.relpath(__file__, ROOT)}", file=sys.stderr)
    return 1


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="do not write; fail if the shipped stylesheet is not the board's")
    parser.add_argument("--board", default=BOARD, help="the design board to read")
    parser.add_argument("--out", default=OUT, help="the module to write")
    parser.add_argument("--pages", default=None, metavar="DIR",
                        help="write the board's screens out again, indented, one file each")
    args = parser.parse_args(argv)

    try:
        with open(args.board, encoding="utf-8") as handle:
            board_text = handle.read()
        wanted = render(board_text)
    except (OSError, ValueError) as exc:
        print(f"X {exc}", file=sys.stderr)
        return 2

    if args.pages:
        try:
            return write_pages(board_text, args.pages)
        except (OSError, ValueError) as exc:
            print(f"X {exc}", file=sys.stderr)
            return 2

    if args.check:
        try:
            with open(args.out, encoding="utf-8") as handle:
                written = handle.read()
        except OSError as exc:
            print(f"X {exc}", file=sys.stderr)
            return 2
        return check(written, wanted)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(wanted)
    print(f"wrote {os.path.relpath(args.out, ROOT)}  ({len(wanted):,} bytes, "
          f"{wanted.count('{')} rules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
